### ISSUE TITLE
Bounce email when following 

### ISSUE THREAD

**Issue by marco-vene** [r-lib/gmailr#56] opened 2016-03-26 14:50 UTC
Hi,

I have some problems with the tutorial on how to send emails with your gmailr package.

The code below returns a bounce mail due to the html_body part. Just if I remove it the email is sent correctly, but without body. Also text_body does not work for me. 

Also, can you advise me on how to send an attachment. (I tried   %>% attach_file("iris.csv") , but that also results in a bounce email.)

```r
test_email <- mime() %>%
 to("to@gmail.com") %>%
 from("from@gmail.com") %>%
 subject("This is a subject") %>%
 html_body("<html><body>I wish <b>this</b> was bold</body></html>")
```

Thanks for the awesome package.

Marco

**Comment by marco-vene** [comment] 2016-03-26 14:54
I sent message with:

ret_val <- send_message(test_email) 
ret_val$status_code 

status_code is 200, but no mail is sent.

**Comment by tmamiya** [comment] 2016-04-05 23:31
I am also curious on how to accomplish this =)

**Comment by jimhester** [comment] 2019-08-15 17:23
The code in the vignette does still work, I just tested it. I imagine the issues were related to the attachments you mention, possibly a duplicate of #81, so I will close this.

**Closed by jimhester** 2019-08-15 17:23 UTC
Labels: bug
