### ISSUE TITLE
No such button "DOWNLOAD CLIENT CONFIGURATION"

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [r-lib/gmailr#149] opened 2021-02-04 17:47 UTC
The documentation states I should click on "DOWNLOAD CLIENT CONFIGURATION" after enabling the Gmail API. But there is no such button in the UI

**Comment by jennybc** [comment] 2021-05-04 16:19
Duplicate of #143

**Closed** 2023-05-02 23:35 UTC
