### ISSUE TITLE
Error in Authenticating

### ISSUE THREAD

**Issue by howard-gu** [r-lib/gmailr#107] opened 2019-02-26 23:37 UTC
Hi there,

Not sure why / what's happening as it this was working fine for me yesterday - however today I'm getting the following error messages when running the code below.

gmail_auth(scope = c("compose"), id = < my id >)

Google Chrome pops up for the authentication process > I select the appropriate gmail account/

Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  : 
  Bad Request (HTTP 400). Failed to get an access token

Does this have something to do with expired tokens? Or is there something else I'm missing?

Thanks!

Cheers,
Howard

**Comment by jimhester** [comment] 2019-08-13 18:03
Not sure, cannot reproduce the issue, so I am going to close this.

**Closed by jimhester** 2019-08-13 18:03 UTC
Labels: reprex
