### ISSUE TITLE
cannot extract the body of a message

### ISSUE THREAD

**Issue by RockScience** [r-lib/gmailr#48] opened 2016-01-28 03:34 UTC
I have tried:

``` r
> y = gmailr::message("15285bb691e1a2b4", user_id = user_id, format = c("full", "minimal", "raw")[1])
# this works and returns a valid gmailr message.

> y$payload$mimeType
[1] "text/html"

> y$payload$body # this returns a format I don't know how to read (64 encoding I guess) 

> y$payload$headers[[25]]
$name
[1] "Mime-Version"
$value
[1] "1.0"

> y$payload$headers[[26]]
$name
[1] "Content-Transfer-Encoding"
$value
[1] "base64"

> RCurl::base64Decode(txt = y$payload$body$data) # this returns a valid html txt, however only the first part is there, using a online tool such as https://www.base64decode.org/, I can get the entire body

#but all the following return an empty list()
y_body = gmailr::body(y, type = "html")
y_body = gmailr::body(y, type = NULL)
y_body = gmailr::body(y, type = "text/plain")
```

Any help would be welcome:
1) is gmailr::body supposed to do the 64 decoding?
2) is there an alternative to get the full body in html?

 Thank you

**Comment by lawremi** [comment] 2016-01-28 21:44
This is essentially a duplicate of #28.

**Comment by jimhester** [comment] 2016-01-28 21:50
@RockScience you need to use `gmailr:::base64url_decode_to_char(y$payload$body$data)` as the emails are [base64 url encoded](https://en.wikipedia.org/wiki/Base64#URL_applications).

@lawremi is correct this a duplicate of #28.

**Comment by RockScience** [comment] 2016-01-29 02:05
I agree it is certainly the same issue as #28 . Should we close the issue or keep it open until #28 is fixed?

@jimhester Thank you I didn;t know this function. I tried `RCurl::base64Decode(txt)` and `paste(rawToChar(base64enc::base64decode(txt), multiple = TRUE),collapse="")` but for whatever reason some special characters are only converted correctly with `gmailr:::base64url_decode_to_char`

**Comment by FranGhelfi** [comment] 2016-09-11 15:05
Hi. I´m trying your answer but I couldn´t get the body.

`lee <- message("15718f593d7e09f7", user_id = "me", format = c("full"))`
`body <- gmailr:::base64url_decode_to_char(lee$payload$body)`

The result " body" is a "" character.

**Comment by phillc73** [comment] 2017-06-12 21:07
Encountered a similar situation. To access the body of the message I've found success using the following:

```r
a_msg <- message(id = "15c9abc7604b823f", format = "full")

msg_body <- gmailr:::base64url_decode_to_char(a_msg$payload$parts[[2]]$parts[[1]]$body$data)
```

**Comment by jimhester** [comment] 2019-08-19 20:55
This is somewhat difficult to reproduce, but I think it has been fixed as part of https://github.com/r-lib/gmailr/pull/35

**Closed by jimhester** 2019-08-19 20:55 UTC
Labels: bug, feature
